### ISSUE TITLE
add comparable function to PartialOrd

### ISSUE THREAD

**Issue by dbeacham** [phadej/lattices#23]
Could we add

```haskell
comparable :: PartialOrd a => a -> a -> Bool
comparable x y = leq x y || leq y x
```

either as a standalone function or a class method on `PartialOrd` with default implementation as above? Only reason I suggest a class method is so that instances could improve performance a touch, but it's possibly only a minor benefit.

Happy to send over a pull request for preferred approach.

**Comment by phadej** [comment]
How that would be different from `Eq`'s `==` ?

**Comment by phadej** [comment]
I'm ok with class method, it would still be a backward compatible change. PR is more then welcome.
