### ISSUE TITLE
Any vs All

### ISSUE THREAD

**Issue by blargg** [phadej/lattices#28]
Based on the names, it seemed like the semi lattice instances for `Any` and `All` should be opposites (roughly, `Any = Op . All`). It looks like `Any` and `All` have the same instances right now.
Would it be better to make `Any` and `All` opposites?

**Comment by phadej** [comment]
The instances are the same as for `Bool`. In the context of `All` and `Any` think `\/` as `||` and `/\` as `&&`.

**Comment by blargg** [comment]
Sounds good to me.
