### ISSUE TITLE
induced JoinSemiLattice from PartialOrd

### ISSUE THREAD

**Issue by carlostome** [phadej/lattices#42]
Hi, I'm interesed in lattices induced by a partial order relation and some extra element that serves as top

We could implement such using the already existing datatype Algebra.Lattice.Dropped but it already has instances for JoinSemiLattice, BoundedSemiLattice ... that would overlap.

I propose to augment the library with something like the following:

```haskell
module Algebra.PartialOrd.Drop where

import Algebra.Lattice
import Algebra.PartialOrd

data Drop a = Topped
            | Dropped a

instance PartialOrd a => JoinSemiLattice (Drop a) where
  Topped    \/ _      = Topped
  _      \/ Topped    = Topped
  Dropped x \/ Dropped y
    | leq x y   = Dropped y
    | leq y x   = Dropped x
    | otherwise = Topped

instance BoundedJoinSemiLattice (Drop a) where
   top = Topped
```
Of course this can be generalized for Lifted, Levitated and maybe something else.

**Comment by phadej** [comment]
Is this correct? Take sets with union as a join, subset as partord. `{1, 2}` and `{2,3}` aren't in relation, yet their union is `{1, 2, 3}`; not a "all numbers".

**Comment by carlostome** [comment]
My use case was to have Int + Top so the partial order between Int is just equality and Top serves to make a JoinSemiLattice out of it.

**Comment by phadej** [comment]
I'm unease to add that to the library. Your use case has quite strong condition of 

*not `(a ≤ b)` and not `(b ≤ a)` imply (a ∨ b)`.

I'd rather implement `instance Eq a => JoinSemiLattice (Something a)` in your executable, as I'm not sure it has a established name or/and is generally useful.

**Comment by carlostome** [comment]
Ok, then I'll close the issue, thanks for answering so quickly.

**Comment by phadej** [comment]
sorry for unable to help more.
