### ISSUE TITLE
Complemented lattice

### ISSUE THREAD

**Issue by jakubdaniel** [phadej/lattices#49]
It would be nice, if this package directly exported

    class BoundedLattice a => ComplementedLattice a where
        complement :: a -> a

or something of that sort.

**Comment by phadej** [comment]
Taken how fine grained this library is atm, we'd need `HeytingAlgebra` in between.

There are heyting algebras which aren't boolean. See https://en.wikipedia.org/wiki/Heyting_algebra

**Comment by phadej** [comment]
Heyting algebra is added
