### ISSUE TITLE
HashMap JoinSemiLattice/MeetSemiLattice instances look wrong

### ISSUE THREAD

**Issue by lambdageek** [phadej/lattices#50]
Maybe I'm missing something, but shouldn't the join/meet semilattice instances for `HashMap k v` be analogous to `Map k v`? That is:

```haskell
instance (Eq k, Hashable k, JoinSemiLattice v) => JoinSemiLattice (HM.HashMap k v) where
  (\/) = HM.unionWith (\/)
```

(and similarly for Meet)

**Comment by lambdageek** [comment]
If nothing else the present instance for `JoinSemiLattice` is wrong since `HM.union` is not commutative.

**Comment by phadej** [comment]
They most likely are, and I'm :+1: for making them the similar to `Map` instances. Also `HashSet` to be similar to `Set`. And we need to add tests for all of them. At least as with `Map`.
