### ISSUE TITLE
Can I haz an lts snapshot in stack.yaml, rather than nightly?

### ISSUE THREAD

**Issue by kindaro** [phadej/lattices#65]
It is a minor issue, but I would much rather build a project with an `lts` snapshot. Some of the packages will be already downloaded, built and cached, so the build will be faster and less hard drive space used.

I would humbly suggest replacing a `nightly-2017-06-01` in `stack.yaml` with an `lts-10.5` or any other `lts` snapshot, especially since this particular nightly [adds nothing](https://github.com/phadej/lattices/issues/64) to the project's buildability.

**Comment by phadej** [comment]
I don't use `stack` actively anymore. Please make a PR to update it.

**Comment by phadej** [comment]
Solved by #67
