### ISSUE TITLE
PartialOrd a => PartialOrd (Lifted a)?

### ISSUE THREAD

**Issue by ocharles** [phadej/lattices#71]
https://hackage.haskell.org/package/lattices-1.7.1.1/docs/Algebra-Lattice-Lifted.html grafts a new least onto an unbounded lattice. Should this have a PartialOrd instance, such that `leq Bottom x = True` for all x?

**Comment by ocharles** [comment]
I note it's also lacking a `Universe` instance, which seems fine if we have `Universe a` (just `fmap Lift` over the existing universe and add `Bottom`).

**Comment by phadej** [comment]
is there instances for Dropped or Leviated (and other wrappers). The PR for adding them will be welcomed

**Comment by ocharles** [comment]
Great, I'll get you a PR. I just wanted to make sure they made sense. `Levitated` and `Dropped` also lack these.

**Comment by phadej** [comment]
Done in https://github.com/phadej/lattices/commit/787b093eeb046a8c8e708e9a547c4d20dbb67b76
